### ISSUE TITLE
Feat: default 이미지 애셋 제작

### ISSUE THREAD

**Issue by se030** [c-h-w-h/aboohae#28]
## 💎 개발할 기능

- [ ] 페이지에서 제공하는 og:image가 없는 경우에 보여줄 이미지가 필요해요

서버에서 넣으려다가 프론트 애셋으로 가지고 있는게 더 좋은 것 같아서 !!

**Comment by se030** [comment]
<img width="520" alt="Thumbnail" src="https://user-images.githubusercontent.com/63814960/224466974-1e3d93c9-ab87-4b05-8a65-7286e7d91c60.png">

어때요

**Comment by iyu88** [comment]
귀여워요~
